sudo: false

language: php
php:
  - 'master'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - lcov

env:
  - RE2C_VERSION="1.1.1"

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.local/opt/re2c
    - ${HOME}/.cache/re2c

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry gem install coveralls-lcov
  - ulimit -c unlimited -S

install:
  - .ci/install-re2c.sh
  - .ci/build.sh

before_script:
  - make coverage-initial

script:
  - .ci/run-tests.sh

jobs:
  include:
    - stage: re2c versions test
      php: 7.2
      env:
        - RE2C_VERSION="0.13.6"
      install:
        - .ci/install-re2c.sh
        - .ci/build.sh
      script:
        - .ci/run-tests.sh
    - stage: re2c versions test
      php: 7.2
      env:
        - RE2C_VERSION="system"
      install:
        - .ci/install-re2c.sh
        - .ci/build.sh
      script:
        - .ci/run-tests.sh

after_failure:
  - .ci/after-failure.sh

after_success:
  - make coverage-capture
  - if [ ! -z "${CODECOV_TOKEN}" ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
