language: php
php:
  - 'nightly'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - lcov

env:
  matrix:
    - RE2C_VERSION="0.13.6"
    - RE2C_VERSION="1.1.1"

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.local/opt
    - ${HOME}/.cache/re2c

before_install:
  - phpenv config-rm xdebug.ini || true
  - ulimit -c unlimited -S

install:
  - .ci/install-re2c.sh
  - phpize
  - aclocal && libtoolize --copy --force && autoheader && autoconf
  - |
      ./configure \
        --with-php-config=$(phpenv which php-config) \
        --enable-zephir-parser \
        --enable-zephir-parser-debug \
        --enable-coverage \
        LDFLAGS="${LDFLAGS} --coverage" \
        CFLAGS="${CFLAGS} -O0 -ggdb -fprofile-arcs -ftest-coverage" \
        CXXFLAGS="${CXXFLAGS} -O0 -ggdb -fprofile-arcs -ftest-coverage"
  - make -j"$(getconf _NPROCESSORS_ONLN)"

before_script:
  - make coverage-initial

script:
  - .ci/run-tests.sh

after_failure:
  - .ci/after-failure.sh

after_success:
  - make coverage-capture
  - if [ ! -z "${CODECOV_TOKEN}" ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
